on: [push]

jobs:
  runTest:
    name: test for Jopi
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: node install
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org'

      - name: Installing Npn & Lerna & Yarn
        run: |
          npm install
          npm install -g npm-cli-login
          npm install --global lerna
          yarn install

      - name: loguearse a npm
        run: npm-cli-login -u ${{ secrets.NPM_USER_NAME }} -p '${{ secrets.NPM_PASSWORD }}' -e ${{ secrets.NPM_EMAIL }}

      - name: se posiciona en la ruta de bin
        run: cd node_modules/.bin

      - name: loguearse a github
        run: |
          git config --global user.email "bsabatino@navent.com"  
          git config --global user.name "bsabatino"

      - name: updetea los paquetes de lerna
        run: lerna version patch --yes

      - name: publica una nueva verion de jopi
        run: lerna publish from-package --yes

      - name: listar
        run: ls
