on: [push]

jobs:
  runTest:
    name: test for Jopi
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: node install
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org'

      - name: Installing Npn & Lerna & Yarn
        run: |
          npm install
          npm install -g npm-cli-login

      - name: Listar tokens
        run: |
          npm-cli-login -u ${{ secrets.NPM_USER_NAME }} -p '${{ secrets.NPM_PASSWORD }}' -e ${{ secrets.NPM_EMAIL }}
          npm token
